# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '
      $headers = @{"Authorization" = "Bearer $env:CIUSERTOKEN"}

      $signingRequestUrl = "https://app.signpath.io/Api/v1/$env:ORGID/SigningRequests/$env:SRID";
      $jsonResponse = ConvertFrom-Json (Invoke-WebRequest -Uri $signingRequestUrl -Headers $headers)

      $signedArtifactLink = $jsonResponse.signedArtifactLink

      $outFile = Join-Path ${env:Build.SourcesDirectory} temp
      Invoke-WebRequest -Uri $signedArtifactLink -OutFile $outFile -Headers $headers'
  env:
    ORGID: $(OrganizationId)
    SRID: $(SigningRequestId)
    CIUSERTOKEN: $(CIUserToken)


