# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '
      $headers = @{"Authorization" = "Bearer $env:CIUSERTOKEN"};

      $signingRequestUrl = "https://app.signpath.io/Api/v1/$env:ORGID/SigningRequests/$env:SRID";
      
      Write-Host "Obtaining information from $signingRequestUrl";
      $jsonResponse = ConvertFrom-Json (Invoke-WebRequest -Uri $signingRequestUrl -Headers $headers);

      $signedArtifactLink = $jsonResponse.signedArtifactLink;
      Write-Host "Obtaining artifact from $signedArtifactLink";
      $outFile = Join-Path $env:BUILD_ARTIFACTSTAGINGDIRECTORY SignPathTestProject.dll;
      Invoke-WebRequest -Uri $signedArtifactLink -OutFile $outFile -Headers $headers;'
  env:
    ORGID: $(OrganizationId)
    SRID: $(SigningRequestId)
    CIUSERTOKEN: $(CIUserToken)

- task: GitHubRelease@0
  inputs:
    gitHubConnection: drauch_3
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    tagSource: 'manual'
    tag: '$(Build.BuildNumber)'
